services:
  - type: web
    name: minecraft-discord-bot
    env: node
    plan: starter
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
  - type: pserv
    name: minecraft-discord-bot-db
    env: postgresql
    plan: starter