services:
  - type: web
    name: minecraft-discord-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
  - type: pserv
    name: minecraft-discord-bot-db
    env: postgresql
    plan: starter