services:
  - type: web
    name: minecraft-discord-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: NPM_CONFIG_PRODUCTION
        value: false